name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os: [ubuntu-20.04]
        dc: [dmd-2.095.0]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install package dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libclang-10-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy

      - name: Install dotnet
        run: |
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get install apt-transport-https
            sudo apt-get update
            sudo apt-get install dotnet-sdk-2.1

      - name: Add to PATH
        run: echo /opt/python/3.9.1/lib >> $GITHUB_PATH

      - name: Run tests
        shell: bash
        run: ci/test-all.sh
        env:
          PYTHON_INCLUDE_DIR: ~/virtualenv/python3.9/include/python3.9
          PYTHON_LIB_DIR: /opt/python/3.9.1/lib
          PYD_LIBPYTHON_DIR: /opt/python/3.9.1/lib
          LD_RUN_PATH: $PYTHON_LIB_DIR:$PYD_LIBPYTHON_DIR
          LIBRARY_PATH: /usr/lib/llvm-10/lib

      - uses: codecov/codecov-action@v1
